# Constants use by generic table widget
FILTER_OPERATOR_CONTAINS = "contains"
FILTER_OPERATOR_BETWEEN = "between"
FILTER_OPERATOR_LESS = "less than"
FILTER_OPERATOR_LESS_EQUAL = "less or equal than"
FILTER_OPERATOR_MORE = "more than"
FILTER_OPERATOR_MORE_EQUAL = "more than"
FILTER_OPERATOR_EQUAL = "equal to"

MAXIBON_DAILY_ACCESS = 1
MAXIBON_PARTY_GUETTA = 2
MAXIBON_PARTY_NIGHT = 3
