# Constants use by generic table widget
FILTER_OPERATOR_CONTAINS = "contains"
FILTER_OPERATOR_BETWEEN = "between"
FILTER_OPERATOR_LESS = "less than"
FILTER_OPERATOR_LESS_EQUAL = "less or equal than"
FILTER_OPERATOR_MORE = "more than"
FILTER_OPERATOR_MORE_EQUAL = "more than"
FILTER_OPERATOR_EQUAL = "equal to"

REWARD_BIG_IMAGE_SIZE = "400x400"
REWARD_MEDIUM_IMAGE_SIZE = "200x200"
REWARD_SMALL_IMAGE_SIZE = "100x100"

MAXIBON_DAILY_ACCESS = 1
MAXIBON_PARTY_GUETTA = 2
MAXIBON_PARTY_NIGHT = 3

INTERACTION_TYPES = Set.new(['Quiz', 'Check', 'Comment', 'Like', 'Play', 'Share'])

REWARDING_RULE_SETTINGS_KEY = 'rewarding.rules'

MEDIA_TYPES = ["IMAGE", "YOUTUBE", "IFRAME", "VOID"]

BYTES_IN_MEGABYTE = 1048576
MAX_UPLOAD_SIZE = 3 #Megabyte (Mb)
