
# name of source db
source_db_name: violetta

# select 'disney' or 'violetta'
source_db_tenant: violetta

# name of destination db
destination_db_name: test_fandom

# tenant of destination db (or null)
destination_db_tenant: disney

# set true to limit users', user_interactions', user_rewards', comments' and votes' table entries (just for testing)
limit_lines: false
